### ISSUE TITLE
Storage delegation API failure

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#190]
When the DA is deployed with KMS CRN provided, the API call to dataplatform storage delegation API fails with the error:

```
2024/10/18 13:05:09 Terraform apply | module.storage_delegation[0].restapi_object.storage_delegation: Creating...
 2024/10/18 13:05:09 Terraform apply | 
 2024/10/18 13:05:09 Terraform apply | Error: unexpected response code '400': {"statusCode":400,"message":"Invalid request body.","errors":[{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"spaces"},"message":"must have required property 'spaces'"}]}
 2024/10/18 13:05:09 Terraform apply | 
 2024/10/18 13:05:09 Terraform apply |   with module.storage_delegation[0].restapi_object.storage_delegation,
 2024/10/18 13:05:09 Terraform apply |   on storage_delegation/main.tf line 53, in resource "restapi_object" "storage_delegation":
 2024/10/18 13:05:09 Terraform apply |   53: resource "restapi_object" "storage_delegation" {
```
I think Watson API introduced a new required attribute which causes the error

### Affected modules

https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/f0cd3ecf9830feff2975ec363cbfcfddb55caaae/storage_delegation/main.tf#L70

*

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by alex-reiff** [comment]
Watson team pushed this breaking change then rolled it back. Draft PR exists if they push the change again: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/191
