### ISSUE TITLE
[terraform-ibm-watsonx-saas-da] Update CRA config to scan DA directory

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#198]
cra-config.yaml should be scanning the DA directory, and using the profile defined in `ibm_catalog.json`

**Comment by kierramarie** [comment]
@ocofaigh In the catalog it lists 1.6.0, is that the version we want to use? And if so, how do I get that profile id?

**Comment by ocofaigh** [comment]
@kierramarie yes use the ID for 1.6.0 (automation will bump it to 1.7.0 after you make the change).
To get the ID just log into an SCC instance in us-south, and get the ID from the profile. The 1.6.0 fscloud profile ID us `bfacb71d-4b84-41ac-9825-e8a3a3eb7405`

(NOTE: The IDs are different per region and our automation is using us-south so hence use a us-south instance.
