### ISSUE TITLE
[terraform-ibm-watsonx-saas-da] Scope KMS policy to the exact KMS key

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#205]
The policy [here](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/3e7d08a611ece83ef2906851b5a91395406dbe19/storage_delegation/main.tf#L12-L19) can be updated to scope it to the exact KMS key. For an example of the syntax, see https://github.com/terraform-ibm-modules/terraform-ibm-cos/pull/764

**Comment by Vipin654** [comment]
CC: @SarikaSinha

**Comment by ocofaigh** [comment]
PR merged - closing
