### ISSUE TITLE
demo project already exists - initial run

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#23]
Seen this error a few times when deploying the DA in an existing account. It seems that the project name is unique per account (regardless of the number of machine learning instance), so suggesting to add a random suffix to the name to avoid clashes.

configure_project | Failed | unexpected response code '400': Project name 'demo' already used.

**Comment by Aashiq-J** [comment]
PR merged. Closing issue
