### ISSUE TITLE
Include resource group ID as output

### ISSUE THREAD

**Issue by brendankellyibm** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#5]
### Description

Include created resource group ID as output - as discussed, we will probably need this in the RAG App DA later.

### New or affected modules

terraform-ibm-watsonx-saas-da

---

**Comment by ocofaigh** [comment]
looks like this was done in https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/8
