### ISSUE TITLE
Split user and project configuration into separate modules

### ISSUE THREAD

**Issue by brendankellyibm** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#6]
### Description

As we need to create a new user (to be confirmed) and a new project (this is confirmed) in the RAG App DA, it makes sense to reuse the same modules used to provision WatsonX AI users/projects in the terraform-ibm-watsonx-saas-da module. Therefore, could we split those modules into their own repositories so they can be reused? 

### New or affected modules

terraform-ibm-watsonx-saas-da

new:
terraform-ibm-watsonx-saas-user
terraform-ibm-watsonx-saas-project

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by vburckhardt** [comment]
I'd suggest going with one repo - terraform-ibm-watsonx-saas - for grouping all reusable watsonx modules. Each module can be in a sub directory in that repo.

**Comment by mkrudele** [comment]
done
