### ISSUE TITLE
Improve description of the variables

### ISSUE THREAD

**Issue by andreainnocenti** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#7]
https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/4#discussion_r1542612475

**Comment by imprateeksh** [comment]
Raised [PR-43](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/43)

**Comment by hlucey** [comment]
Another PR [here](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/42)
@imprateeksh @andreainnocenti

**Comment by imprateeksh** [comment]
The PR has been merged. Hence closing the issue.
