### ISSUE TITLE
Support deploying some of the watson services in jp-tok region.

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-watsonx-saas-da#89]
### Description

Use case: some customers want to deploy some of the watson services in jp-tok region. 

Issue: currently, the location field is set to allow only the regions that are supported by ALL watson service.

2 approaches:
- In the location field - add all regions supported by at least one watson service. Add some static checks in the terraform logic to error out if the users selected to deploy a service in a region that is not supported
- Or, add an optional region input for each watson service

**Comment by andreainnocenti** [comment]
The cleanest way is to use this feature https://github.com/hashicorp/terraform/issues/25609 at plan time. Unfortunatly terraform v1.9 is not yet available and we don't know when it will be avaliable in Schematics. 

Let's do this with a check block https://developer.hashicorp.com/terraform/language/checks, do you agree?

**Comment by vburckhardt** [comment]
@andreainnocenti - here is an example of the way it is typically done with current version of terraform. https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/05e504dbd0e3057171616ec98bfb9f96d7d45813/main.tf#L22

check block assertion cannot be applied here as they won't block execution (just surface a warning)

**Comment by mkrudele** [comment]
Before going ahead and implement, we must first understand if the watsonx platform works with services deployed in different regions, and which ones can be deployed in different regions.

**Comment by andreainnocenti** [comment]
| Service                 | Regions                                    |
|-------------------------|--------------------------------------------|
| Watson Machine Learning | jp-tok,eu-gb,eu-de,us-south                |
| Watson Studio           | jp-tok,eu-gb,eu-de,us-south                |
| watsonx.governance      | eu-de,us-south                             |
| watsonx Assistant       | au-syd,jp-tok,eu-gb,eu-de,us-south,us-east |
| Watson Discovery        | au-syd,jp-tok,eu-gb,eu-de,us-south,us-east |

**Comment by andreainnocenti** [comment]
the final decision was to allow the regions jp-tok,eu-gb,eu-de,us-south and add a check on watsonx.governance
```
  lifecycle {
    precondition {
      condition     = contains(["eu-de", "us-south"], var.location)
      error_message = "Watwatsonx.governance is only available in eu-de and us-south region."
    }
  }
```
in this way the plan fails
<img width="645" alt="Screenshot 2024-06-21 at 07 47 10" src="https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/assets/62945651/57740306-1ecc-43c3-9cc0-fb67e0384950">
